name: Validate OSSP Events

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install validators
        run: npm install ajv@8 ajv-formats@3
      - name: Validate sample events
        run: node scripts/validate.js
